In [1]:
import pandas as pd

# Load the data
df = pd.read_csv('WB_WDI_SE_PRM_UNER.csv')

# Look at the first 5 rows 
df.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VNM,WB_WDI_SE_PRM_UNER,_T,_T,_T,CH,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,PSE,WB_WDI_SE_PRM_UNER,_T,_T,_T,CH,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZMB,WB_WDI_SE_PRM_UNER,_T,_T,_T,CH,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VEN,WB_WDI_SE_PRM_UNER,_T,_T,_T,CH,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VNM,WB_WDI_SE_PRM_UNER,_T,_T,_T,CH,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public

In [ ]:
# number of rows and columns in the dataset
df.shape

(4526, 43)

In [2]:
# understand the structure 
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4526 entries, 0 to 4525
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               4526 non-null   object
 1   STRUCTURE_ID            4526 non-null   object
 2   ACTION                  4526 non-null   object
 3   FREQ                    4526 non-null   object
 4   REF_AREA                4526 non-null   object
 5   INDICATOR               4526 non-null   object
 6   SEX                     4526 non-null   object
 7   AGE                     4526 non-null   object
 8   URBANISATION            4526 non-null   object
 9   UNIT_MEASURE            4526 non-null   object
 10  COMP_BREAKDOWN_1        4526 non-null   object
 11  COMP_BREAKDOWN_2        4526 non-null   object
 12  COMP_BREAKDOWN_3        4526 non-null   object
 13  TIME_PERIOD             4526 non-null   int64
 14  AGG_METHOD              4526 non-null   object
 15  UNIT_TYPE               4526 non-null   object
 16  DECIMALS                4526 non-null   int64
 17  DATABASE_ID             4526 non-null   object
 18  TIME_FORMAT             4526 non-null   object
 19  COMMENT_TS              4526 non-null   object
 20  UNIT_MULT               4526 non-null   int64
 21  DATA_SOURCE             4526 non-null   object
 22  OBS_CONF                4526 non-null   object
 23  OBS_VALUE               4526 non-null   float64
 24  OBS_STATUS              4526 non-null   object
 25  FREQ_LABEL              4526 non-null   object
 26  REF_AREA_LABEL          4526 non-null   object
 27  INDICATOR_LABEL         4526 non-null   object
 28  SEX_LABEL               4526 non-null   object
 29  AGE_LABEL               4526 non-null   object
 30  URBANISATION_LABEL      4526 non-null   object
 31  UNIT_MEASURE_LABEL      4526 non-null   object
 32  COMP_BREAKDOWN_1_LABEL  4526 non-null   object
 33  COMP_BREAKDOWN_2_LABEL  4526 non-null   object
 34  COMP_BREAKDOWN_3_LABEL  4526 non-null   object
 35  AGG_METHOD_LABEL        4526 non-null   object
 36  UNIT_TYPE_LABEL         4526 non-null   object
 37  DECIMALS_LABEL          4526 non-null   object
 38  DATABASE_ID_LABEL       4526 non-null   object
 39  TIME_FORMAT_LABEL       4526 non-null   object
 40  UNIT_MULT_LABEL         4526 non-null   object
 41  OBS_STATUS_LABEL        4526 non-null   object
 42  OBS_CONF_LABEL          4526 non-null   object
dtypes: float64(1), int64(3), object(39)
memory usage: 1.5+ MB
None

In [3]:
# columns of the dataset
df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'TIME_PERIOD', 'AGG_METHOD',
       'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT', 'COMMENT_TS',
       'UNIT_MULT', 'DATA_SOURCE', 'OBS_CONF', 'OBS_VALUE', 'OBS_STATUS',
       'FREQ_LABEL', 'REF_AREA_LABEL', 'INDICATOR_LABEL', 'SEX_LABEL',
       'AGE_LABEL', 'URBANISATION_LABEL', 'UNIT_MEASURE_LABEL',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL', 'UNIT_TYPE_LABEL',
       'DECIMALS_LABEL', 'DATABASE_ID_LABEL', 'TIME_FORMAT_LABEL',
       'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL', 'OBS_CONF_LABEL'],
      dtype='object')

In [4]:
# unique values in the AGE column
print(df['AGE'].unique())

['_T']

In [5]:
# unique values in sex column
print(df['SEX'].unique())

['_T']

In [11]:
# number of countries in the dataset
print("Number of countries in the dataset:",len(df['REF_AREA_LABEL'].unique()))

Number of countries in the dataset: 209

In [12]:
# check for missing values
df.isnull().sum()

STRUCTURE                 0
STRUCTURE_ID              0
ACTION                    0
FREQ                      0
REF_AREA                  0
INDICATOR                 0
SEX                       0
AGE                       0
URBANISATION              0
UNIT_MEASURE              0
COMP_BREAKDOWN_1          0
COMP_BREAKDOWN_2          0
COMP_BREAKDOWN_3          0
TIME_PERIOD               0
AGG_METHOD                0
UNIT_TYPE                 0
DECIMALS                  0
DATABASE_ID               0
TIME_FORMAT               0
COMMENT_TS                0
UNIT_MULT                 0
DATA_SOURCE               0
OBS_CONF                  0
OBS_VALUE                 0
OBS_STATUS                0
FREQ_LABEL                0
REF_AREA_LABEL            0
INDICATOR_LABEL           0
SEX_LABEL                 0
AGE_LABEL                 0
URBANISATION_LABEL        0
UNIT_MEASURE_LABEL        0
COMP_BREAKDOWN_1_LABEL    0
COMP_BREAKDOWN_2_LABEL    0
COMP_BREAKDOWN_3_LABEL    0
AGG_METHOD_LABEL          0
UNIT_TYPE_LABEL           0
DECIMALS_LABEL            0
DATABASE_ID_LABEL         0
TIME_FORMAT_LABEL         0
UNIT_MULT_LABEL           0
OBS_STATUS_LABEL          0
OBS_CONF_LABEL            0
dtype: int64

In [13]:
# check for duplicates
df.duplicated().sum()

np.int64(0)

In [14]:
# Select relevant columns and rename
df_clean = df[['REF_AREA_LABEL', 'TIME_PERIOD', 'OBS_VALUE', 'AGE', 'SEX']].copy()
df_clean.columns = ['Country', 'Year', 'Children_Out_of_School', 'Age', 'Sex']
df_clean.head()

              Country  Year  Children_Out_of_School Age Sex
0             Vietnam  2009           146927.000000  _T  _T
1  West Bank and Gaza  2009            40965.000000  _T  _T
2              Zambia  2009           234997.000000  _T  _T
3       Venezuela, RB  2014           232348.000000  _T  _T
4             Vietnam  2014            23805.853563  _T  _T

In [15]:
df_clean["Age"] = df_clean["Age"].replace("_T", "Total")
df_clean["Sex"] = df_clean["Sex"].replace("_T", "Total")
df_clean.head()

              Country  Year  Children_Out_of_School    Age    Sex
0             Vietnam  2009           146927.000000  Total  Total
1  West Bank and Gaza  2009            40965.000000  Total  Total
2              Zambia  2009           234997.000000  Total  Total
3       Venezuela, RB  2014           232348.000000  Total  Total
4             Vietnam  2014            23805.853563  Total  Total

In [16]:
# Check for duplicates in cleaned data
df_clean.duplicated().sum()

np.int64(0)

In [17]:
# Sort the data
df_clean = df_clean.sort_values(['Country', 'Year']).reset_index(drop=True)